#!/usr/bin/env python3
#
# Copyright (C) 2026 Neil Rackett
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Builds the cartridge payload image: the files INSTALL.PRG writes to the
# ST's STinG folder, laid out so the m68k can read them straight out of
# the ROM4 window. Emits a C header the RP firmware stages into that
# window (see rp/src/payload.c).
#
# Keeping the layout here means the installer and the firmware cannot
# disagree about it: there is exactly one place that decides.
#
#   usage: mkpayload.py <out.h> NAME=path [NAME=path ...]

import os
import struct
import sys

PAYLOAD_OFF = 0x6000  # m68k offset from $FA0000; above the RX buffer
DATA_START = 0x100  # leaves room for (0x100-8)/24 = 10 entries
ENT_SIZE = 24
NAME_LEN = 16
REGION_END = 0x10000  # ROM4 window is 64 KB


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: mkpayload.py <out.h> NAME=path [NAME=path ...]")

    out_path = sys.argv[1]
    files = []
    for arg in sys.argv[2:]:
        name, _, path = arg.partition("=")
        if not path:
            sys.exit("bad argument %r, expected NAME=path" % arg)
        with open(path, "rb") as handle:
            files.append((name, handle.read()))

    if len(files) * ENT_SIZE + 8 > DATA_START:
        sys.exit("too many payload entries for the directory area")

    # Directory first, then the file data, each entry 2-byte aligned so
    # the m68k can read it without care.
    blob = bytearray(DATA_START)
    blob[0:4] = b"MDNP"
    struct.pack_into(">HH", blob, 4, 1, len(files))

    for index, (name, data) in enumerate(files):
        encoded = name.encode("ascii")
        if len(encoded) >= NAME_LEN:
            sys.exit("payload name too long: %s" % name)
        offset = PAYLOAD_OFF + len(blob)
        blob += data
        if len(blob) & 1:
            blob += b"\x00"
        entry = 8 + index * ENT_SIZE
        blob[entry:entry + NAME_LEN] = encoded.ljust(NAME_LEN, b"\x00")
        struct.pack_into(">II", blob, entry + NAME_LEN, offset, len(data))

    end = PAYLOAD_OFF + len(blob)
    if end > REGION_END:
        sys.exit("payload overflows the ROM4 window: 0x%X > 0x%X"
                 % (end, REGION_END))

    lines = [
        "// Generated by tools/mkpayload.py -- do not edit.",
        "// Files installed on the ST by INSTALL.PRG, staged into the",
        "// cartridge ROM4 window by rp/src/payload.c.",
        "#ifndef MDNET_PAYLOAD_H",
        "#define MDNET_PAYLOAD_H",
        "",
        "#include <stdint.h>",
        "",
        "#define MDNET_PAYLOAD_OFF 0x%04Xu" % PAYLOAD_OFF,
        "",
        "static const uint8_t mdnet_payload[] = {",
    ]
    for start in range(0, len(blob), 12):
        chunk = blob[start:start + 12]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))
    lines += ["};", "", "#endif  // MDNET_PAYLOAD_H", ""]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))

    print("payload: %d file(s), %d bytes, $FA%04X-$FA%04X"
          % (len(files), len(blob), PAYLOAD_OFF, end))
    for name, data in files:
        print("         %-14s %6d bytes" % (name, len(data)))


if __name__ == "__main__":
    main()
